from .unet_model import UNet
from .deeplabv3 import DeepLabV3Plus
from .resnet import ResNet50WithUpsampling,ResNet34WithUpsampling
from .dlink import DinkNet34
from .pspnet import PSPNet
from .ukan import UKAN
from .dVitUnet import DVit_net
from .Hrnet_w18_ocr import HRNet_W48_OCR
from .mix_transformer import SegFormer